# Generated by Django 5.1.3 on 2024-11-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostreamer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to='media/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='media/videos/'),
        ),
    ]
